kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skjdev
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ghost
  name: skjdev-conf
data:
  production.json: |
    {
      "url": "https://skj.dev",
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "mariadb.db.svc",
          "port": 3306,
          "database": "ghost_skjdev"
        }
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: skjdev
  namespace: ghost
spec:
  selector:
    matchLabels:
      app: skjdev
  replicas : 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skjdev
    spec:
      nodeName: elrond
      containers:
        - image: library/ghost:4.22.4
          name: skjdev
          env:
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: skjdev-db
                  key: dbuser
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: skjdev-db
                  key: dbpass
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: skjdev
              mountPath: /var/lib/ghost/content
            - name: skjdev-conf
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
      volumes:
        - name: skjdev
          persistentVolumeClaim:
            claimName: skjdev
        - name: skjdev-conf
          configMap:
            name: skjdev-conf
            items:
              - key: production.json
                path: config.production.json

---
apiVersion: v1
kind: Service
metadata:
  name: skjdev
  namespace: ghost
  labels:
    app: skjdev
spec:
  ports:
    - name: server
      port: 80
      targetPort: 2368
  selector:
    app: skjdev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skjdev
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: skj.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skjdev
                port:
                  number: 80
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: static
                port:
                  number: 80

  tls:
    - hosts:
        - skj.dev
        - www.skj.dev
      secretName: skj-dev-cert

