---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: db
data:
  custom.cnf: |
    [mysqld]
    bind-address = 0.0.0.0

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
  namespace: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: db
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: "elrond"
      containers:
      - image: mariadb:10.7.1
        name: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadbroot
                key: passwd
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
        - name: config
          mountPath: "/etc/mysql/conf.d/custom.cnf"
          subPath: "custom.cnf"
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
      - name: config
        configMap:
          name: mariadb
---
kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: db
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
