kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: splashofink
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ghost
  name: splashofink-conf
data:
  production.json: |
    {
      "url": "https://splashof.ink",
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "mariadb.db.svc",
          "port": 3306,
          "database": "ghost_splashofink"
        }
      },
      "mail": {
        "transport": "SMTP",
        "options": {
          "service": "Mailgun",
          "host": "smtp.mailgun.org",
          "port": 465,
          "secureConnection": true
        }
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: splashofink
  namespace: ghost
spec:
  selector:
    matchLabels:
      app: splashofink
  replicas : 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: splashofink
    spec:
      nodeName: elrond
      containers:
        - image: library/ghost:4.22.4
          name: splashofink
          env:
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: splashofink-db
                  key: dbuser
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: splashofink-db
                  key: dbpass
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: mailgun-splashofink
                  key: user
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mailgun-splashofink
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: splashofink
              mountPath: /var/lib/ghost/content
            - name: splashofink-conf
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
      volumes:
        - name: splashofink
          persistentVolumeClaim:
            claimName: splashofink
        - name: splashofink-conf
          configMap:
            name: splashofink-conf
            items:
              - key: production.json
                path: config.production.json

---
apiVersion: v1
kind: Service
metadata:
  name: splashofink
  namespace: ghost
  labels:
    app: splashofink
spec:
  ports:
    - name: server
      port: 80
      targetPort: 2368
  selector:
    app: splashofink
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splashofink
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: splashof.ink
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: splashofink
                port:
                  number: 80
  tls:
    - hosts:
        - splashof.ink
        - www.splashof.ink
      secretName: splashof-ink-cert

