apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
  namespace: plex
spec:
  capacity:
    storage: 60Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /plex
    server: 10.0.1.55
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  storageClassName: nfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 60Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
  namespace: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - image: plexinc/pms-docker:1.25.3.5409-f11334058
          name: plex
          env:
            - name: HOSTNAME
              value: "TVC15"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-transcode
              mountPath: /transcode
            - name: plex-media
              mountPath: /media
              readOnly: true
          resources:
            limits:
              gpu.intel.com/i915: 1
      securityContext:
        fsGroup: 1000
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-transcode
          emptyDir: {}
        - name: plex-media
          persistentVolumeClaim:
            claimName: plex-media
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  selector:
    app: plex
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 32400
      name: plex


